export interface SkipCategoryDef {
  label: string
  badge: string       // full tailwind classes for the badge chip
  description: string // shown in the specialty section header tooltip / sub-text
}

export const CATEGORY_DEFS: Record<string, SkipCategoryDef> = {
  'commercial-roofing': {
    label: 'Commercial Roofing',
    badge: 'bg-violet-100 text-violet-700',
    description: 'TPO, PVC, modified bitumen — flat/low-slope systems, not residential',
  },
  'solar': {
    label: 'Solar',
    badge: 'bg-amber-100 text-amber-800',
    description: 'Integrated solar roofing — different install workflow from shingles',
  },
  'insulation': {
    label: 'Insulation',
    badge: 'bg-sky-100 text-sky-700',
    description: 'Rigid board, batt, and spray insulation — not a roofing surface product',
  },
  'interior': {
    label: 'Interior Products',
    badge: 'bg-slate-100 text-slate-600',
    description: 'Drywall, ceiling tiles, and wall systems — unrelated to roofing',
  },
  'coatings': {
    label: 'Roof Coatings',
    badge: 'bg-teal-100 text-teal-700',
    description: 'Commercial acrylic/silicone coatings — applied over existing flat roofs',
  },
  'millwork': {
    label: 'Millwork & Columns',
    badge: 'bg-rose-100 text-rose-700',
    description: 'Decorative columns, railings, and exterior millwork — not roofing',
  },
  'decking': {
    label: 'Decking & Structural',
    badge: 'bg-orange-100 text-orange-700',
    description: 'Composite decking and structural lumber products',
  },
  'fasteners-commercial': {
    label: 'Commercial Fasteners',
    badge: 'bg-gray-200 text-gray-600',
    description: 'Mechanical fasteners for commercial flat-roofing systems',
  },
  'acoustic': {
    label: 'Acoustic / Specialty',
    badge: 'bg-lime-100 text-lime-700',
    description: 'Acoustic dampeners and specialty building products',
  },
  'tools': {
    label: 'Tools',
    badge: 'bg-gray-200 text-gray-600',
    description: 'Application tools and accessories',
  },
}

// Ordered list of prefix → category key per brand.
// First match wins (same startsWith logic as shouldSkipByDefault).
const BRAND_SKIP_CATEGORIES: Record<string, { prefix: string; category: string }[]> = {
  Gaf: [
    { prefix: 'EverGuard',                 category: 'commercial-roofing' },
    { prefix: 'RUBEROID',                  category: 'commercial-roofing' },
    { prefix: 'GAFGLAS',                   category: 'commercial-roofing' },
    { prefix: 'LIBERTY SBS',               category: 'commercial-roofing' },
    { prefix: 'LIBERTY Asphalt',           category: 'commercial-roofing' },
    { prefix: 'LIBERTY Flashing',          category: 'commercial-roofing' },
    { prefix: 'Tri-Ply',                   category: 'commercial-roofing' },
    { prefix: 'Timberline S1',             category: 'solar' },
    { prefix: 'Timberline Solar',          category: 'solar' },
    { prefix: 'United Coatings',           category: 'coatings' },
    { prefix: 'HydroStop',                 category: 'coatings' },
    { prefix: 'MATRIX',                    category: 'coatings' },
    { prefix: 'Unisil',                    category: 'coatings' },
    { prefix: 'OlyBond',                   category: 'coatings' },
    { prefix: 'OMG OlyBond',               category: 'coatings' },
    { prefix: 'Acrylex',                   category: 'coatings' },
    { prefix: 'Bleed-Block',               category: 'coatings' },
    { prefix: 'MajorSeal',                 category: 'coatings' },
    { prefix: 'TopCoat',                   category: 'coatings' },
    { prefix: 'TOPCOAT',                   category: 'coatings' },
    { prefix: 'WOD Acrylic',               category: 'coatings' },
    { prefix: 'CleanAct',                  category: 'coatings' },
    { prefix: 'EnergyCote',                category: 'coatings' },
    { prefix: 'Acrylic HydroStop',         category: 'coatings' },
    { prefix: 'High-Tensile Acrylic',      category: 'coatings' },
    { prefix: 'Hydrostop',                 category: 'coatings' },
    { prefix: 'Spray-Grade Acrylic',       category: 'coatings' },
    { prefix: 'Masonex',                   category: 'coatings' },
    { prefix: 'Premium Brush-Grade',       category: 'coatings' },
    { prefix: 'Premium Acrylic',           category: 'coatings' },
    { prefix: 'FlexSeal',                  category: 'coatings' },
    { prefix: 'Fibered Silicone',          category: 'coatings' },
    { prefix: 'Thermoplastic',             category: 'coatings' },
    { prefix: 'SPF Flashing',              category: 'coatings' },
    { prefix: 'Epoxy Primer',              category: 'coatings' },
    { prefix: 'Multi-Purpose Primer',      category: 'coatings' },
    { prefix: 'UniBase',                   category: 'coatings' },
    { prefix: 'XR-2000',                   category: 'coatings' },
    { prefix: 'SureBond',                  category: 'coatings' },
    { prefix: 'M-BOND',                    category: 'coatings' },
    { prefix: 'Lock-Down',                 category: 'coatings' },
    { prefix: 'Bonding Primer',            category: 'coatings' },
    { prefix: 'DEXcell',                   category: 'insulation' },
    { prefix: 'EnergyGuard',               category: 'insulation' },
    { prefix: 'DensDeck',                  category: 'insulation' },
    { prefix: 'USG Securock',              category: 'insulation' },
    { prefix: 'ThermaCal',                 category: 'insulation' },
    { prefix: 'EPS Polystyrene',           category: 'insulation' },
    { prefix: 'STRUCTODEK',                category: 'insulation' },
    { prefix: 'VersaShield',               category: 'insulation' },
    { prefix: 'Drill-Tec',                 category: 'fasteners-commercial' },
    { prefix: 'ASAP Assembled',            category: 'fasteners-commercial' },
    { prefix: 'Heavy Duty ASAP',           category: 'fasteners-commercial' },
    { prefix: 'XHD ASAP',                  category: 'fasteners-commercial' },
    { prefix: 'OlyBond500',                category: 'fasteners-commercial' },
    { prefix: 'M-WELD',                    category: 'commercial-roofing' },
    { prefix: 'M-Thane',                   category: 'commercial-roofing' },
    { prefix: 'M-Curb',                    category: 'commercial-roofing' },
    { prefix: 'FireOut',                   category: 'commercial-roofing' },
    { prefix: 'SA PRIMER',                 category: 'commercial-roofing' },
    { prefix: 'Self-Adhered Vapor',        category: 'commercial-roofing' },
    { prefix: 'PVC Membrane Conditioner',  category: 'commercial-roofing' },
    { prefix: 'PVC Square',                category: 'commercial-roofing' },
    { prefix: 'TPO Drain',                 category: 'commercial-roofing' },
    { prefix: 'TPO Solvent',               category: 'commercial-roofing' },
    { prefix: 'TPO WB181',                 category: 'commercial-roofing' },
    { prefix: 'TPO Quick Hose',            category: 'commercial-roofing' },
    { prefix: 'TPO Self-Adhered',          category: 'commercial-roofing' },
    { prefix: 'TPO Seam',                  category: 'commercial-roofing' },
    { prefix: 'TPO with',                  category: 'commercial-roofing' },
    { prefix: 'WeatherSide',               category: 'commercial-roofing' },
    { prefix: 'Hand Roof Brush',           category: 'tools' },
    { prefix: 'Roller Cover',              category: 'tools' },
    { prefix: 'Cleaning Concentrate',      category: 'tools' },
  ],

  Certainteed: [
    { prefix: 'GlasRoc',                   category: 'interior' },
    { prefix: 'M2Tech',                    category: 'interior' },
    { prefix: 'VinylShield',               category: 'interior' },
    { prefix: 'Symphony m',                category: 'interior' },
    { prefix: 'THEATRE',                   category: 'interior' },
    { prefix: 'Fine Fissured',             category: 'interior' },
    { prefix: 'Cashmere',                  category: 'interior' },
    { prefix: 'Sand Micro',                category: 'interior' },
    { prefix: 'Sereno',                    category: 'interior' },
    { prefix: 'Baroque',                   category: 'interior' },
    { prefix: 'EZ Stab',                   category: 'interior' },
    { prefix: 'EZ Set',                    category: 'interior' },
    { prefix: 'Drywall',                   category: 'interior' },
    { prefix: 'Regular Drywall',           category: 'interior' },
    { prefix: 'No-Coat',                   category: 'interior' },
    { prefix: 'VINYLROCK',                 category: 'interior' },
    { prefix: 'Magoxide',                  category: 'interior' },
    { prefix: 'FibraFuse',                 category: 'interior' },
    { prefix: 'FibaFuse',                  category: 'interior' },
    { prefix: 'Easi-Lite',                 category: 'interior' },
    { prefix: 'Easi-Tex',                  category: 'interior' },
    { prefix: 'SilentFX',                  category: 'interior' },
    { prefix: 'MARCO',                     category: 'interior' },
    { prefix: 'Levelline',                 category: 'interior' },
    { prefix: 'Quickspan',                 category: 'interior' },
    { prefix: 'Galvanized Wall',           category: 'interior' },
    { prefix: 'Galvanized Narrow',         category: 'interior' },
    { prefix: 'School Board',              category: 'interior' },
    { prefix: 'Open Plan',                 category: 'interior' },
    { prefix: 'Envirogard',                category: 'interior' },
    { prefix: 'Aquarock',                  category: 'interior' },
    { prefix: 'Extreme Abuse',             category: 'interior' },
    { prefix: 'Lite All Purpose',          category: 'interior' },
    { prefix: 'Lite Finishing',            category: 'interior' },
    { prefix: 'All Weather',               category: 'interior' },
    { prefix: 'Black Diamond',             category: 'interior' },
    { prefix: 'Type C',                    category: 'interior' },
    { prefix: 'Type X',                    category: 'interior' },
    { prefix: 'Flintlastic',               category: 'commercial-roofing' },
    { prefix: 'Flintglas',                 category: 'commercial-roofing' },
    { prefix: 'Flintclad',                 category: 'commercial-roofing' },
    { prefix: 'FLINTGLAS',                 category: 'commercial-roofing' },
    { prefix: 'Glasbase',                  category: 'commercial-roofing' },
    { prefix: 'FlintBoard',                category: 'commercial-roofing' },
    { prefix: 'FlintBond',                 category: 'commercial-roofing' },
    { prefix: 'FlintPrime',                category: 'commercial-roofing' },
    { prefix: 'FlintFast',                 category: 'commercial-roofing' },
    { prefix: 'FlintPatch',                category: 'commercial-roofing' },
    { prefix: 'FlintRock',                 category: 'commercial-roofing' },
    { prefix: 'DryRoof',                   category: 'commercial-roofing' },
    { prefix: 'Arctic Edge',               category: 'commercial-roofing' },
    { prefix: 'SMARTFAB',                  category: 'commercial-roofing' },
    { prefix: 'SMARTCOAT',                 category: 'commercial-roofing' },
    { prefix: 'SmartFlash',                category: 'commercial-roofing' },
    { prefix: 'Smartcoat',                 category: 'commercial-roofing' },
    { prefix: 'Smartflash',                category: 'commercial-roofing' },
    { prefix: 'Ultra Flintlastic',         category: 'commercial-roofing' },
    { prefix: 'CertaSeam',                 category: 'commercial-roofing' },
    { prefix: 'CertaTape',                 category: 'commercial-roofing' },
    { prefix: 'Grace VYCOR',               category: 'commercial-roofing' },
    { prefix: 'Solstice',                  category: 'solar' },
    { prefix: 'Green Glue',                category: 'acoustic' },
    { prefix: 'STONEfaçade',               category: 'millwork' },
    { prefix: 'Restoration Millwork',      category: 'millwork' },
    { prefix: 'Kingston',                  category: 'millwork' },
    { prefix: 'Oxford',                    category: 'millwork' },
    { prefix: '1-Piece',                   category: 'millwork' },
    { prefix: '2-Piece',                   category: 'millwork' },
    { prefix: '4-Piece',                   category: 'millwork' },
    { prefix: 'Certa-Snap',                category: 'millwork' },
    { prefix: 'Square Column',             category: 'millwork' },
    { prefix: 'Round Non-Tapered',         category: 'millwork' },
    { prefix: 'Square Blank',              category: 'millwork' },
    { prefix: 'New England External',      category: 'millwork' },
    { prefix: 'Flat External',             category: 'millwork' },
    { prefix: 'Flat Wood Post',            category: 'millwork' },
    { prefix: 'Decorative Post',           category: 'millwork' },
    { prefix: 'Decorative Porch',          category: 'millwork' },
    { prefix: 'Structural Colonial',       category: 'millwork' },
    { prefix: 'Structural Square',         category: 'millwork' },
    { prefix: 'Square Cap',                category: 'millwork' },
    { prefix: 'Routed System',             category: 'millwork' },
    { prefix: 'Handrail',                  category: 'millwork' },
    { prefix: 'Double Channel',            category: 'millwork' },
    { prefix: 'Perimeter Vinyl Triple',    category: 'millwork' },
    { prefix: 'STBAR',                     category: 'millwork' },
    { prefix: 'TrueTexture',               category: 'millwork' },
    { prefix: 'Scratch & Dent',            category: 'millwork' },
    { prefix: 'Shadow Molding',            category: 'millwork' },
    { prefix: 'InsulSafe',                 category: 'insulation' },
    { prefix: 'Batt Fiberglass',           category: 'insulation' },
    { prefix: 'Easi',                      category: 'interior' },
    { prefix: 'ProPink ComfortSeal',       category: 'insulation' },
    { prefix: 'RISE',                      category: 'millwork' },
  ],

  'Owens Corning': [
    { prefix: 'FOAMULAR',                  category: 'insulation' },
    { prefix: 'PINK Next Gen',             category: 'insulation' },
    { prefix: 'Thermafiber',               category: 'insulation' },
    { prefix: 'ProPink',                   category: 'insulation' },
    { prefix: 'AttiCat',                   category: 'insulation' },
    { prefix: 'ProCat',                    category: 'insulation' },
    { prefix: 'Insulation Next Gen',       category: 'insulation' },
    { prefix: 'M62Q',                      category: 'insulation' },
    { prefix: 'BILD-R-TAPE',               category: 'insulation' },
    { prefix: 'Raft-R-Mate',               category: 'insulation' },
    { prefix: 'WEARDECK',                  category: 'decking' },
    { prefix: 'Structural Composite',      category: 'decking' },
    { prefix: 'Solar Attic',               category: 'solar' },
    { prefix: 'PINKWRAP',                  category: 'insulation' },
    { prefix: 'SmartCap Attic Light',      category: 'tools' },
    { prefix: 'Trumbull',                  category: 'commercial-roofing' },
    { prefix: 'Attic Stairway',            category: 'tools' },
    { prefix: 'OC FOAMULAR',               category: 'insulation' },
  ],
}

export function getSkipCategory(brand: string, productLine: string): string | null {
  const entries = BRAND_SKIP_CATEGORIES[brand] ?? []
  const lower = productLine.toLowerCase()
  const match = entries.find(e => lower.startsWith(e.prefix.toLowerCase()))
  return match?.category ?? null
}
